FPT-Libol-master/Libol/Libol/Controllers/PatronController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.SqlServer;
using System.Data.OleDb;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using Libol.Models;
using Libol.SupportClass;
using OfficeOpenXml;
using Libol.EntityResult;
namespace Libol.Controllers
{
    public class PatronController : Controller
    {
        private LibolEntities db = new LibolEntities();
        ExportExcelWithManyRowSearchPatron excelEdit = new ExportExcelWithManyRowSearchPatron();
        [AuthAttribute(ModuleID = 2, RightID = "0")]
        public ActionResult PatronProfile()
        {
            return View();
        }

        [AuthAttribute(ModuleID = 2, RightID = "1")]
        public ActionResult SearchPatronFilter()
        {
            ViewBag.PatronGroup = db.SP_PAT_GET_PATRONGROUP().ToList();
            ViewBag.Faculty = db.CIR_DIC_FACULTY.Select(a => a.Faculty).Distinct().ToList();
            ViewBag.Occupation = db.SP_PAT_GET_OCCUPATION().ToList();
            return View();
        }

        [AuthAttribute(ModuleID = 2, RightID = "2,3")]
        public ActionResult Create(string strPatronID)
        {

            ViewBag.Ethnic = db.SP_PAT_GET_ETHNIC().ToList();
            ViewBag.PatronGroup = db.SP_PAT_GET_PATRONGROUP().ToList();
            ViewBag.Education = db.SP_PAT_GET_EDUCATION().ToList();
            ViewBag.Occupation = db.SP_PAT_GET_OCCUPATION().ToList();
            ViewBag.College = db.SP_PAT_GET_COLLEGE().ToList();
            int CollegeID = db.SP_PAT_GET_COLLEGE().ToList()[0].ID;
            ViewBag.Faculty = db.CIR_DIC_FACULTY.Where(a => a.CollegeID == CollegeID).ToList();
            ViewBag.Province = db.CIR_DIC_PROVINCE.ToList();
            ViewBag.Countries = db.SP_GET_COUNTRIES().ToList();


            if (!String.IsNullOrEmpty(strPatronID))
            {
                int id = Int32.Parse(strPatronID);
                var patron = db.CIR_PATRON.Where(a => a.ID == id).Count() == 0 ? null : db.CIR_PATRON.Where(a => a.ID == id).First();
                if (patron != null)
                {
                    if (patron.CIR_PATRON_UNIVERSITY != null)
                    {
                        ViewBag.Faculty = db.CIR_DIC_FACULTY.Where(a => a.CollegeID == patron.CIR_PATRON_UNIVERSITY.CollegeID).ToList();
                    }

                    return View(patron);
                }
                else
                {
                    return View(new CIR_PATRON());
                }
            }
            else
            {
                return View(new CIR_PATRON());
            }

        }



        [HttpPost]

        public JsonResult changeCollege(string College)
        {
            int CollegeID = db.CIR_DIC_COLLEGE.Where(e => e.College.Contains(College)).Select(e => e.ID).FirstOrDefault();
            ViewBag.Faculty = db.CIR_DIC_FACULTY.Where(a => a.CollegeID == CollegeID).ToList();
            List<CIR_DIC_FACULTY> list = new List<CIR_DIC_FACULTY>();
            foreach (var f in ViewBag.Faculty)
            {
                list.Add(new CIR_DIC_FACULTY()
                {
                    ID = f.ID,
                    Faculty = f.Faculty,
                    CollegeID = f.CollegeID
                });
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult OnchangeCollege(int CollegeID)
        {
            ViewBag.Faculty = db.CIR_DIC_FACULTY.Where(a => a.CollegeID == CollegeID).ToList();
            List<CIR_DIC_FACULTY> list = new List<CIR_DIC_FACULTY>();
            foreach (var f in ViewBag.Faculty)
            {
                list.Add(new CIR_DIC_FACULTY()
                {
                    ID = f.ID,
                    Faculty = f.Faculty,
                    CollegeID = f.CollegeID
                });
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult displayFaculty(int FacultyID)
        {
            List<string> list = new List<string>();
            list = db.CIR_DIC_FACULTY.Where(e => e.ID == FacultyID).Select(e => e.Faculty).ToList();
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        [AuthAttribute(ModuleID = 2, RightID = "2")]
        public JsonResult NewPatron(string strCode, string strValidDate, string strExpiredDate, string strLastIssuedDate, string strLastName, string strFirstName,
             Nullable<bool> blnSex, string strDOB, Nullable<int> intEthnicID, Nullable<int> intEducationID, Nullable<int> intOccupationID,
            string strWorkPlace, string strTelephone, string strMobile, string strEmail, string strPortrait, Nullable<int> intPatronGroupID, string strNote,
            Nullable<int> intIsQue, string strIDCard, string strAddress, Nullable<int> intProvinceID, string strCity, Nullable<int> intCountryID, string strZip,
            Nullable<int> intisActive, int intCollegeID, int intFacultyID, string strGrade, string strClass)
        {
            string InvalidFields = "";
            if (String.IsNullOrEmpty(strFirstName))
            {
                InvalidFields += "strFirstName-";
            }
            if (String.IsNullOrEmpty(strLastName))
            {
                InvalidFields += "strLastName-";
            }
            if (String.IsNullOrEmpty(strDOB))
            {
                InvalidFields += "strDOB-";
            }
            if (String.IsNullOrEmpty(strCode))
            {
                InvalidFields += "strCode-";
            }
            if (intPatronGroupID == null)
            {
                InvalidFields += "intPatronGroupID-";
            }
            if (String.IsNullOrEmpty(strValidDate))
            {
                InvalidFields += "strValidDate-";
            }
            if (String.IsNullOrEmpty(strExpiredDate))
            {
                InvalidFields += "strExpiredDate-";
            }
            if (String.IsNullOrEmpty(strLastIssuedDate))
            {
                InvalidFields += "strLastIssuedDate-";
            }
            //if (intCollegeID == -1)
            //{
            //    InvalidFields += "college-";
            //}
            //if (intFacultyID == -1)
            //{
            //    InvalidFields += "faculty-";
            //}
            if (String.IsNullOrEmpty(strWorkPlace))
            {
                InvalidFields += "strWorkPlace-";
            }
            if (String.IsNullOrEmpty(strAddress))
            {
                InvalidFields += "strAddress-";
            }
            if (String.IsNullOrEmpty(strEmail))
            {
                InvalidFields += "strEmail-";
            }

            if (InvalidFields != "")
            {
                return Json(new Result()
                {
                    CodeError = 1,
                    Data = InvalidFields
                }, JsonRequestBehavior.AllowGet);
            }
            else
            if (db.CIR_PATRON.Where(a => a.Code == strCode).Count() > 0)
            {
                return Json(new Result()
                {
                    CodeError = 2,
                    Data = "Bạn đọc với số thẻ " + strCode + " đã tồn tại!"
                }, JsonRequestBehavior.AllowGet);
            }
            else
            if (db.CIR_PATRON.Where(a => a.Code != strCode && a.Email == strEmail).Count() > 0)
            {
                return Json(new Result()
                {
                    CodeError = 2,
                    Data = "Email " + strEmail + " không hợp lệ!"
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                //string strMiddleName = "";
                //if (strFirstName.Split(' ').Length > 1)
                //{
                //    List<string> names = strFirstName.Split(' ').ToList();
                //    string firstName = names.First();
                //    names.RemoveAt(0);
                //    strMiddleName = string.Join(",", names);
                //    strFirstName = firstName;
                //}
                string strMiddleName = "";
                string[] resultName;
                string firstName = "";
                string middleName = "";
                string lastName = "";
                char[] splitchar2 = { ' ' };
                int stop = 0;
                //if (strFirstName.Split(' ').Length > 1)
                //{
                //    List<string> names = strFirstName.Split(' ').ToList();
                //    string firstName = names.First();
                //    names.RemoveAt(0);
                //    strMiddleName = string.Join(",", names);
                //    strFirstName = firstName;
                //}
                resultName = strFirstName.Split(splitchar2);
                for (int count = 0; count <= resultName.Length; count++)
                {
                    stop++;
                    if (resultName.Length == 4)
                    {
                        firstName = resultName[0].Trim();
                        middleName = resultName[1].Trim() + " " + resultName[2].Trim() + " " + resultName[3].Trim();

                    }
                    else if (resultName.Length == 5)
                    {
                        firstName = resultName[0].Trim();
                        middleName = resultName[1].Trim() + " " + resultName[2].Trim() + " " + resultName[3].Trim() + " " + resultName[4].Trim();

                    }
                    else if (resultName.Length == 3)
                    {
                        firstName = resultName[0].Trim();
                        middleName = resultName[1].Trim() + " " + resultName[2].Trim();

                    }
                    else if (resultName.Length == 2)

FPT-Libol-master/Libol/Libol/Views/Patron/AddPatronByFile.cshtml
@{
    ViewBag.Title = "Thêm bạn đọc theo lô";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h4 style="margin : 1rem">Thêm bạn đọc theo lô</h4>
@using (Html.BeginForm("PreviewPatronFile", "Patron", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">

        <label for="exampleFormControlFile1">Vui lòng chọn file</label>
        <input name="uploadFile" type="file" class="form-control-file" id="filePatron" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">


    </div>
    <button type="submit" class="btn btn-primary">OK</button>

    <p>(Click vào <a href="~/Content/Template1/Template_Import_Patron.xlsx">đây</a> để tải template)</p>
}

FPT-Libol-master/Libol/Libol/Views/Patron/AdjournPatronExpiredDateByList.cshtml
@{
    ViewBag.Title = "Gia hạn đọc theo lô";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*START------------SCRIPT FOR DATATABLES*@
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.css">
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/Select-1.3.0/css/select.bootstrap4.css">
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/dataTables.checkboxes.css">
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/Select-1.3.0/js/dataTables.select.js"></script>

<h4 style="margin : 1rem">Gia hạn bạn đọc theo lô</h4>
<p>(Mỗi số thẻ bạn đọc cách nhau bởi enter. Cick vào <a href="#" onclick="ShowExample();">đây</a> để xem mẫu.)</p>
<form>
    <div class="form-row">
        <div class="col-4">
            <div class="form-group">
                <textarea class="form-control" id="strPatronCodes" rows="15"></textarea>
            </div>
            <div class="form-group">
                <input type="date" class="form-control " id="newExpiredDate">
            </div>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirmAdjourn">Gia hạn</button>
        </div>
        <div class="col-8" id="hiddenNotify" style="display:none;">
            <label style="color:red;">Những bạn đọc sau không thể gia hạn. Vui lòng kiểm tra lại.</label>
            <table id="table-fail" class="table table-striped table-bordered datatables" style="width: 100%;">
                <thead>
                    <tr>
                        <th>Số thẻ</th>
                        <th>Họ tên</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="col-8" id="hiddenNotifySuccess" style="display:none;">
            <label style="color:green;">Gia hạn thành công.</label>
        </div>
        <div class="col-8" id="hiddenNotifySelectionDate" style="display:none;">
            <label style="color:red;">Vui lòng chọn ngày.</label>
        </div>
    </div>


</form>

<div class="modal" tabindex="-1" role="dialog" id="confirmAdjourn">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Xác nhận gia hạn bạn đọc</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Bạn có chắc chắn muốn gia hạn?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-warning" onclick="AdjournPatronExpiredDate()">Gia hạn</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="loadingDialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Vui lòng chờ</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Loading . . .</p>
            </div>
            <div class="modal-footer">

            </div>
        </div>
    </div>
</div>

<script>
    function ShowExample() {
        document.getElementById("strPatronCodes").value = "SE01234\nSE01235\nSE01236";
    }
    function AdjournPatronExpiredDate() {
        if (document.getElementById("newExpiredDate").value == "") {
            document.getElementById("hiddenNotifySelectionDate").style.display = "block";
            $("#confirmAdjourn").modal("hide");
        } else {
            document.getElementById("hiddenNotifySelectionDate").style.display = "none";
            document.getElementById("hiddenNotify").style.display = "none";
            document.getElementById("hiddenNotifySuccess").style.display = "none";
            $("#confirmAdjourn").modal("hide");
            $("#loadingDialog").modal();
            var empObj = {
                strPatronCodes: document.getElementById("strPatronCodes").value,
                newExpiredDate: document.getElementById("newExpiredDate").value
            };
            $.ajax({
                url: "/Patron/AdjournPatronExpiredDate",
                data: JSON.stringify(empObj),
                type: "POST",
                contentType: "application/json;charset=utf-8",
                dataType: "json",
                success: function (result) {
                    if (result[0] != null) {
                        $('#table-fail').DataTable({
                            destroy: true,
                            data: result
                        });
                        document.getElementById("hiddenNotify").style.display = "block";
                    }
                    else {
                        document.getElementById("hiddenNotifySuccess").style.display = "block";
                    }
                    $("#loadingDialog").modal("hide");

                },
                error: function (errormessage) {

                }
            });
        }
    }
</script>

FPT-Libol-master/Libol/Libol/Views/Patron/DeletePatronsByList.cshtml
@{
    ViewBag.Title = "Xóa bạn đọc theo lô";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*START------------SCRIPT FOR DATATABLES*@
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.css">
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/Select-1.3.0/css/select.bootstrap4.css">
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/dataTables.checkboxes.css">
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/Select-1.3.0/js/dataTables.select.js"></script>

<h4 style="margin : 1rem">Xóa bạn đọc theo lô</h4>
<p>(Mỗi số thẻ bạn đọc cách nhau bởi enter. Cick vào <a href="#" onclick="ShowExample();">đây</a> để xem mẫu.)</p>
<form>
    <div class="form-row">
        <div class="col-4">
            <div class="form-group">
                <textarea class="form-control" id="strPatronCodes" rows="15"></textarea>
            </div>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#confirmDelete">Xóa</button>
        </div>
        <div class="col-8" id="hiddenNotify" style="display:none;">
            <label style="color:red;">Những bạn đọc sau không thể xóa. Vui lòng kiểm tra lại.</label>
            <table id="table-fail" class="table table-striped table-bordered datatables" style="width: 100%;">
                <thead>
                    <tr>
                        <th>Số thẻ</th>
                        <th>Họ tên</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div class="col-8" id="hiddenNotifySuccess" style="display:none;">
            <label style="color:green;">Xóa thành công.</label>

        </div>
    </div>


</form>

<div class="modal" tabindex="-1" role="dialog" id="confirmDelete">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Xác nhận xóa bạn đọc</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Bạn có chắc chắn muốn xóa?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-danger" onclick="DeletePatrons()">Xóa</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" tabindex="-1" role="dialog" id="loadingDialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Vui lòng chờ</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Loading . . .</p>
            </div>
            <div class="modal-footer">
                
            </div>
        </div>
    </div>
</div>

<script>
    function ShowExample() {
        document.getElementById("strPatronCodes").value = "SE01234\nSE01235\nSE01236";
    }
    function DeletePatrons() {
        document.getElementById("hiddenNotify").style.display = "none";
        document.getElementById("hiddenNotifySuccess").style.display = "none";
        $("#confirmDelete").modal("hide");
        $("#loadingDialog").modal();
        var empObj = {
            strPatronCodes: document.getElementById("strPatronCodes").value
        };
        $.ajax({
            url: "/Patron/DeletePatrons",
            data: JSON.stringify(empObj),
            type: "POST",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                if (result[0] != null) {
                    $('#table-fail').DataTable({
                        destroy: true,
                        data: result
                    });
                    document.getElementById("hiddenNotify").style.display = "block";
                }
                else {
                    document.getElementById("hiddenNotifySuccess").style.display = "block";                    
                }
                $("#loadingDialog").modal("hide");
                
            },
            error: function (errormessage) {

            }
        });
    }
</script>

FPT-Libol-master/Libol/Libol/Views/Patron/PreviewPatronFile.cshtml
@using Libol.SupportClass;
@using Libol.Controllers;
@{
    ViewBag.Title = "Thêm bạn đọc theo lô";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*START------------SCRIPT FOR DATATABLES*@
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/DataTables-1.10.18/css/dataTables.bootstrap4.css">
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/Select-1.3.0/css/select.bootstrap4.css">
<link rel="stylesheet" type="text/css" href="~/Content/DataTables/dataTables.checkboxes.css">
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/DataTables-1.10.18/js/jquery.dataTables.js"></script>
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/DataTables-1.10.18/js/dataTables.bootstrap4.js"></script>
<script type="text/javascript" charset="utf8" src="~/Content/DataTables/Select-1.3.0/js/dataTables.select.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#table_patron').DataTable({

        });
        var message = '@ViewBag.MessageFail';
            $.alert({
                title: 'Thông Báo !',
                content: message ,

            });



    });
    function AddPatronByExcel() {
        $.ajax({
            url: "/Patron/AddPatronByExcel",
            type: "POST",
            contentType: "application/json;charset=utf-8",
            dataType: "json",
            success: function (result) {
                //alert('Bạn đã thanh lý sản phẩm thành công');

                //alert(result);
                $.alert({
                    title: 'Thông Báo !',
                    content: result.Message,

                });


            },
            error: function () {
                alert('Thêm không thành công');
            }

        });
    }
</script>
<h4 style="margin : 1rem">Thêm bạn đọc theo lô</h4>
<div style="margin-top: 1rem">
    <h5 style="text-align: center; color:green;">Danh sách bạn đọc từ File!</h5>
    <table id="table_patron" class="table table-striped table-bordered datatables">
        <thead>
            <tr>
                <th>STT</th>
                <th>Mã sinh viên</th>
                <th>Họ và tên</th>
                <th>Giới tính</th>
                <th>Ngày sinh</th>
                <th>Email</th>
                <th>Địa chỉ thường trú</th>
                <th>Chuyên ngành</th>
                <th>Điện thoại</th>
                <th>Khoá</th>
                <th>Trường</th>
                <th>Thành phố</th>
                <th>Lớp</th>
                <th>Nhóm</th>
                <th>Sửa</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.ListTotal)
            {
                <tr>

                    <td>@item.ID</td>
                    @if (item.FailPosition.Contains("code") || item.Code == "")
                    {
                        <td style="background-color:red">@item.Code</td> }
                    else
                    {
                        <td>@item.Code</td>}


                    @if (item.FirstName == "" || item.LastName == "")
                    {
                        <td style="background-color:red">@item.FirstName @item.MiddleName @item.LastName</td> }
                    else
                    {
                        <td>@item.FirstName @item.MiddleName @item.LastName</td>}

                    @if (item.Sex == "")
                    {
                        <td style="background-color:red">@item.Sex</td> }
                    else
                    {
                        <td>@item.Sex</td>}

                    @if (item.FailPosition.Contains("dob") || item.DOB == "")
                    {
                        <td style="background-color:red">@item.DOB</td> }
                    else
                    {
                        <td>@item.DOB</td>}

                    @if (item.FailPosition.Contains("email") || item.Email == "")
                    {
                        <td style="background-color:red">@item.Email</td> }
                    else
                    {
                        <td>@item.Email</td>}

                    @if (item.Address == "")
                    {
                        <td style="background-color:red">@item.Address</td> }
                    else
                    {
                        <td>@item.Address</td>}

                    @if (item.FailPosition.Contains("faculty") || item.Faculty == "")
                    {
                        <td style="background-color:red">@item.Faculty</td> }
                    else
                    {
                        <td>@item.Faculty</td>}

                    @if (item.Mobile == "")
                    {
                        <td style="background-color:red">@item.Mobile</td> }
                    else
                    {
                        <td>@item.Mobile</td>}

                    @if (item.Grade == "")
                    {
                        <td style="background-color:red">@item.Grade</td> }
                    else
                    {
                        <td>@item.Grade</td>}

                    @if (item.College == "")
                    {
                        <td style="background-color:red">@item.College</td> }
                    else
                    {
                        <td>@item.College</td>}

                    @if (item.City == "")
                    {
                        <td style="background-color:red">@item.City</td> }
                    else
                    {
                        <td>@item.City</td>}
                    <td>@item.Class</td>


                    @if (item.PatronGroup == "")
                    {
                        <td style="background-color:red">@item.PatronGroup</td> }
                    else
                    {
                        <td>@item.PatronGroup</td>}
                    <td>@Html.ActionLink("Sửa", "Edit", "Patron", new { id = item.ID }, htmlAttributes: new { @class = "btn btn-primary" })</td>
                </tr>
            }
            @foreach (var item in ViewBag.ListPatron)
            {
                <tr>
                    <td>@item.ID</td>
                    <td>@item.Code</td>
                    <td>@item.FirstName @item.MiddleName @item.LastName</td>

                    <td>@item.Sex</td>
                    <td>@item.DOB</td>
                    <td>@item.Email</td>
                    <td>@item.Address</td>
                    <td>@item.Faculty</td>
                    <td>@item.Mobile</td>
                    <td>@item.Grade</td>
                    <td>@item.College</td>
                    <td>@item.City</td>
                    <td>@item.Class</td>
                    <td>@item.PatronGroup</td>
                    <td>@Html.ActionLink("Sửa", "Edit", "Patron", new { id = item.ID }, htmlAttributes: new { @class = "btn btn-primary" })</td>

                </tr>
            }
        </tbody>

    </table>
</div>



<div class="info-form" style="text-align:center">
    <p><button type="button" class="btn btn-success " onclick="AddPatronByExcel()">Thêm bạn đọc</button></p>

</div>